# Generated by Django 3.2.2 on 2021-11-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211127_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
